SELECT
  contractVersion,
  evidenceId,
  sourceRequestId,
  connectExecutionId,
  connectRequestId,
  lookupKeyType,
  lookupCanonicalKey,
  lookupAddress,
  lookupParcelId,
  providerId,
  providerVersion,
  evidenceLevel,
  sourceUrl,
  sourceIdentity,
  publisherId,
  sourceDomain,
  retrievedAt,
  sourcePublishedAt,
  httpStatus,
  retrievalOutcome,
  retrievalAttempts,
  contentType,
  failureCode,
  evidenceKind,
  exactPropertyMatch,
  indexCompletenessVerified,
  listingStatus,
  rawStatus,
  askingPriceAmountMinor,
  askingPriceCurrency,
  askingPriceParseStatus,
  evidenceExcerpt,
  primaryRawArtifactUri,
  primaryRawArtifactSha256,
  evidenceFieldsJson,
  provenanceJson,
  sourceRecordJson,
  sourceRecordSha256
FROM target_normalized_evidence
WHERE
  retrievalOutcome = 'SUCCESS'
  AND evidenceKind = 'exact_listing'
  AND exactPropertyMatch = TRUE
